// "Sunlit Paper" primitives — the only permitted building blocks for
// dashboard UI (docs/DASHBOARD-UX-BLUEPRINT.md §4.8).
export { default as DashProvider } from './DashProvider'
export { default as DashCard } from './DashCard'
export { default as StatTile } from './StatTile'
export { default as HeroGreeting } from './HeroGreeting'
export { default as ViewTabs } from './ViewTabs'
export { default as StatusPill } from './StatusPill'
export { default as SegmentPill } from './SegmentPill'
export { default as DottedRow } from './DottedRow'
export { default as Timeline } from './Timeline'
export { default as Sheet } from './Sheet'
export { default as ConfirmDialog } from './ConfirmDialog'
export { default as PeekPanel } from './PeekPanel'
export { default as GlassBar } from './GlassBar'
export { default as CommandPalette } from './CommandPalette'
export { default as EmptyState } from './EmptyState'
export { default as LedgerTable } from './LedgerTable'
export { default as FreshnessStamp } from './FreshnessStamp'
export { default as CoachMarks, useTourOffer, TourOfferStrip, TourHelpButton } from './CoachMarks'
export { TOURS } from './tours'
export { default as ShortcutsSheet } from './ShortcutsSheet'
export { SkeletonTile, SkeletonRow } from './Skeleton'
export { default as useScrollLock } from './useScrollLock'
